token = ""

### Get all students
GET http://localhost:8080/students

### Get one student
GET http://localhost:8080/students/1

### add new student
POST http://localhost:8080/students
Content-Type: application/json

{
  "name": "Alex",
  "age": 18,
  "gender": "NB",
  "classYear": 2022,
  "present": false
}

### Update
PUT http://localhost:8080/students/1
Content-Type: application/json

{
  "name": "Definitely Alex"
}

### Delete
DELETE http://localhost:8080/students/1


### Faculty Get all
GET http://localhost:8080/faculty

### Faculty get one
GET http://localhost:8080/faculty/1

### Add faculty
POST http://localhost:8080/faculty
Content-Type: application/json

{
  "name": "Fakumrah",
  "age": 56,
  "gender": "Male",
  "subjectTeacher": "Physics"
}

### Update Faculty
PUT http://localhost:8080/faculty/1
Content-Type: application/json

{
  "name": "Fahk Yu",
  "age": 56,
  "gender": "Female",
  "subjectTeacher": "Physics"
}

### Delete faculty
DELETE http://localhost:8080/faculty/1

### authentication register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Fakumrah",
  "age": 56,
  "gender": "Male",
  "subjectTeacher": "Physics",
  "email": "fakumrah@email.com",
  "password": "password"
}

### authentication authenticate
POST http://localhost:8080/auth/authentication
