server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/student # path is to specific models within db
    username: avrr
    password: posAbe123!@#

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  main:
    web-application-type: servlet
